/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "BetterAuthSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Bus": {
      "arn": string
      "name": string
      "type": "sst.aws.Bus"
    }
    "BusToRealtime": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Config": {
      "githubUrl": string
      "name": string
      "type": "sst.sst.Linkable"
    }
    "DebugFunction": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "DefaultBus": {
      "arn": string
      "name": string
      "type": "sst.aws.Bus"
    }
    "Docs": {
      "type": "sst.aws.Astro"
      "url": string
    }
    "DynamoST": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Email": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "GitHubClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GitHubClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NeonDatabaseUrl": {
      "type": "sst.sst.Linkable"
      "url": string
    }
    "NeonPassword": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NeonProdBranchId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NeonProjectId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NextApp": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "Realtime": {
      "authorizer": string
      "endpoint": string
      "type": "sst.aws.Realtime"
    }
    "TestBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Urls": {
      "awsymphonyUrl": string
      "docsUrl": string
      "domain": string
      "type": "sst.sst.Linkable"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}